image: gcc

build-quad:
  stage: build
  before_script:
    - apt update && apt -y install make
  script:
    - cd test
    - make test_quad
  artifacts:
    paths:
      - ./test/test_quad
      - ./test/quad.gcno

test-quad:
  stage: test
  before_script:
    - apt update && apt -y install gcovr
  script:
    - cd test
    - ./test_quad 
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    reports:
      cobertura: ./test/coverage.xml
  needs: ["build-quad"]

build-table:
  stage: build
  before_script:
    - apt update && apt -y install make
  script:
    - cd test
    - make test_table
  artifacts:
    paths:
      - ./test/test_table
      - ./test/table.gcno

test-table:
  stage: test
  before_script:
    - apt update && apt -y install gcovr
  script:
    - cd test
    - ./test_table 
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    reports:
      cobertura: ./test/coverage.xml
  needs: ["build-table"]

build-decaf:
  stage: build
  before_script:
    - apt update && apt -y install make flex bison
  script:
    - make
  artifacts:
    paths:
      - ./decaf

test-decaf:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: test
  before_script:
    - apt update && apt -y install spim ssh
  script:
    - ./dts/run.sh
  needs: ["build-decaf"]

doc:
  image: alpine
  stage: deploy
  before_script:
    - apk update && apk add doxygen graphviz ttf-freefont make
  script:
  - make doc
  - mv doc/html/ public/
  artifacts:
    paths:
    - public