image: gcc

build-quad:
  stage: build
  before_script:
    - apt update && apt -y install make
  script:
    - cd test
    - make test_quad
  artifacts:
    paths:
      - ./test/test_quad

test-quad:
  stage: test
  script:
    - cd test
    - ./test_quad 
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage-quad.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    reports:
      cobertura: test/coverage-quad.xml
  needs: ["build-quad"]

build-table:
  stage: build
  before_script:
    - apt update && apt -y install make
  script:
    - cd test
    - make test_table
  artifacts:
    paths:
      - ./test/test_table

test-table:
  stage: test
  script:
    - cd test
    - ./test_table 
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage-table.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    reports:
      cobertura: test/coverage-table.xml
  needs: ["build-table"]
